Repository apache/flink, pull requests merged in 2019-03, with the labels that each got.

#7874 [FLINK-11752] [dist] Move flink-python to opt (backport)
  flink-dist/src/main/assemblies/bin.xml
  flink-dist/src/main/assemblies/opt.xml
  flink-dist/src/main/flink-bin/bin/pyflink.bat
  flink-dist/src/main/flink-bin/bin/pyflink.sh
Labels: review=description?

#7706 [FLINK-11617] [kinesis] Kinesis Connector getRecords() failure logging is misleading
  flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java
Labels: review=approved ✅

#7679 [FLINK-11501][Kafka Connector] Add ratelimiting to Kafka consumer
  flink-connectors/flink-connector-kafka-0.10/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer010.java
  flink-connectors/flink-connector-kafka-0.10/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010Fetcher.java
  flink-connectors/flink-connector-kafka-0.10/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010FetcherTest.java
  flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer09.java
  flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka09Fetcher.java
  flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThread.java
  flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/Kafka09ITCase.java
  flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka09FetcherTest.java
  flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThreadTest.java
  flink-core/pom.xml
  flink-core/src/main/java/org/apache/flink/api/common/io/ratelimiting/FlinkConnectorRateLimiter.java
  flink-core/src/main/java/org/apache/flink/api/common/io/ratelimiting/GuavaFlinkConnectorRateLimiter.java
Labels: review=approved ✅

#7879 [FLINK-11791] Describe how to build Flink with Hadoop in build guide
  docs/flinkDev/building.md
Labels: review=approved ✅

#7867 [hotfix][datastream] Fix typos in DataStream
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/JoinedStreams.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/WindowedStream.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/OneInputTransformation.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/TwoInputTransformation.java
Labels: review=description?

#7747 [FLINK-11653][DataStream] Add configuration to enforce custom UID's o…
  docs/ops/upgrading.md
  flink-core/src/main/java/org/apache/flink/api/common/ExecutionConfig.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/StreamingJobGraphGeneratorNodeHashTest.java
Labels: review=approved ✅

#7898 [FLINK-11803][table-planner-blink] Improve FlinkTypeFactory for Blink
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkTypeFactory.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkTypeSystem.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/ArrayRelDataType.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/InlineTable.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/MapRelDataType.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/RowRelDataType.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/RowSchema.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/calcite/FlinkTypeFactoryTest.scala
Labels: review=description?

#7905 [FLINK-11826] [hotfix] Ignore flaky testRateLimitedConsumer
  flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/Kafka09ITCase.java
Labels: review=description?

#7909 [FLINK-11833] [State Backends] Cleanup unnecessary createKeyedStateBackend methods in StateBackend
  flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java
  flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateServerTest.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackend.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/HeapKeyedStateBackendAsyncByDefaultTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendMigrationTestBase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/StateBackendTestContext.java
  flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBAsyncSnapshotTest.java
  flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBRocksStateKeysIteratorTest.java
  flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/TriggerTestHarness.java
Labels: review=description?

#7916 [hotfix][flink-core] fix errors in MemorySegment description
  flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
Labels: review=description?

#7907 [FLINK-11829][checkpoint] Avoid FsCheckpointStateOutputStream to store state in files when size below fileStateThreshold
  flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateOutputStreamTest.java
Labels: review=description?

#7830 [hotfix] Reduce and simplify code for column creation in RocksDB backend
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBPriorityQueueSetFactory.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/AbstractRocksDBRestoreOperation.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBFullRestoreOperation.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBNoneRestoreOperation.java
  flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/ttl/RocksDbTtlCompactFiltersManager.java
Labels: review=description?

#7910 [FLINK-11834] [table-planner-blink] Introduce flink logical relational nodes
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkTypeFactory.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/FlinkRelNode.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/Expand.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/LogicalExpand.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/LogicalRank.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/LogicalSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/LogicalWatermarkAssigner.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/Rank.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/Sink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/calcite/WatermarkAssigner.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalAggregate.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalCalc.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalCorrelate.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalDataStreamTableScan.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalExpand.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalIntersect.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalJoin.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalMinus.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalOverWindow.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalRank.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalSort.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalTableFunctionScan.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalTableSourceScan.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalUnion.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalValues.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalWatermarkAssigner.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/DataStreamTable.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/FlinkRelOptTable.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/TableSourceTable.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/TimeIndicatorRelDataType.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/AggregateUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/CalcUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/FlinkRelMdUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/FlinkRelOptUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/SortUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sources/BatchTableSource.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sources/StreamTableSource.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sources/TableSourceUtil.scala
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/type/InternalTypes.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/type/TimestampType.java
Labels: review=description?

#7687 [FLINK-11542][config][docs] Extend memory configuration descriptions
  docs/_includes/generated/task_manager_configuration.html
  docs/_includes/generated/task_manager_memory_configuration.html
  docs/ops/config.md
  flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
Labels: review=approved ✅

#7774 [FLINK-11689] Code clean for streamJobGraphGenerator.
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
Labels: review=approved ✅

#7918 [FLINK-11846] Don't delete HA job files in case of duplicate job submission
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
Labels: review=description?

#7919 [BP-1.8][FLINK-11846] Don't delete HA job files in case of duplicate job submission
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
Labels: review=description?

#7923 [FLINK-11703][table-planner-blink] Introduce TableEnvironments and support registerDataStream and sqlQuery
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/StreamTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/Table.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/TableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/java/StreamTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/DataStreamConversions.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/StreamTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/package.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkCalciteSqlValidator.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkPlannerImpl.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkRelBuilder.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkRelOptClusterFactory.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/schema/RelTable.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/typeutils/TimeIndicatorTypeInfo.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
Labels: review=description?

#7944 [FLINK-11863][table-runtime-blink] Introduce channel to read and write compressed data
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/AbstractChannelReaderInputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/AbstractChannelWriterOutputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/ChannelReaderInputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/HeaderlessChannelReaderInputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/memory/AbstractPagedInputView.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/ChannelWithMeta.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedBlockChannelReader.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedBlockChannelWriter.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelReaderInputView.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelWriterOutputView.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/HeaderlessChannelWriterOutputView.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/FileChannelUtil.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelTest.java
Labels: review=description?

#7945 [FLINK-11857][table-runtime-blink] Introduce BinaryExternalSorter and BufferedKVExternalSorter to batch table runtime
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/BooleanComparator.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/ByteComparator.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/CharComparator.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/IntComparator.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/LongComparator.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/NormalizedKeyUtil.java
  flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/ShortComparator.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/ChannelReaderInputViewIterator.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/HeaderlessChannelReaderInputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/memory/AbstractPagedInputView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/memory/AbstractPagedOutputView.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/api/TableConfigOptions.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/BinaryString.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/compression/BlockCompressionFactory.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedBlockChannelReader.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/AbstractBinaryExternalMerger.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryExternalMerger.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryExternalSorter.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryInMemorySortBuffer.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryIndexedSortable.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryKVExternalMerger.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryKVInMemorySortBuffer.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryMergeIterator.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BufferedKVExternalSorter.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/ChannelReaderKVInputViewIterator.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/ListMemorySegmentPool.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/NormalizedKeyComputer.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/RecordComparator.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/SortUtil.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/SpillChannelManager.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/MemorySegmentPool.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/AbstractRowSerializer.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/BaseRowSerializer.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/BinaryRowSerializer.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/dataformat/BinaryRowTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/dataformat/BinaryStringTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/BinaryExternalSorterTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/BinaryMergeIteratorTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/BufferedKVExternalSorterTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/IntNormalizedKeyComputer.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/IntRecordComparator.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/SortUtilTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/sort/TestMemorySegmentPool.java
Labels: review=description?

#7947 [FLINK-11867]Mistaking in checking filePath's value
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
Labels: review=description?

#7954 [FLINK-11420][datastream][bp-1.7] Fix duplicate and createInstance methods of CoGroupedStreams.UnionSerializer
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/CoGroupedStreams.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/datastream/UnionSerializerTest.java
Labels: review=description?

#7943 [FLINK-11861][tests] Fix JobMasterTriggerSavepointIT not executed
  flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointITCase.java
Labels: review=description?

#7922 [FLINK-10756][runtime][tests] Wait for TM processes to shutdown
  flink-tests/src/test/java/org/apache/flink/test/recovery/AbstractTaskManagerProcessFailureRecoveryTest.java
Labels: review=description?

#7964 [FLINK-11886] [doc] update the output of start/stop_cluster.sh in job…
  docs/ops/jobmanager_high_availability.md
Labels: review=description?

#7946 [FLINK-11866][python] documentation still shows old function
  docs/dev/batch/python.md
Labels: review=description?

#7933 [FLINK-11845][metrics] Drop legacy InfoMessage
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/messages/InfoMessage.java
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/messages/RegisterInfoMessageListener.java
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/messages/UnRegisterInfoMessageListener.java
  flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/InfoMessageListenerRpcGateway.java
  flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
  flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java
  flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/utils/TestingResourceManagerGateway.java
Labels: review=description?

#7970 [FLINK-11874][checkpoint] Split CheckpointStorage interface to distinguish JM and TM side
  flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorage.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageCoordinatorView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageWorkerView.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorage.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/memory/MemoryBackendCheckpointStorage.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/testutils/BackendForTestStream.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/StateBackendTestContext.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/GenericWriteAheadSink.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamTask.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamTaskBuilder.java
Labels: review=description?

#7984 [FLINK-11904][tests]Improve MemoryStateBackendTest by using JUnit's Parameterized
  flink-runtime/src/test/java/org/apache/flink/runtime/state/AsyncMemoryStateBackendTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/MemoryStateBackendTest.java
Labels: review=description?

#7973 [FLINK-11903][tests]Improve FileStateBackendTest by using JUnit's parameterized.
  flink-runtime/src/test/java/org/apache/flink/runtime/state/AsyncFileStateBackendTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/FileStateBackendTest.java
Labels: review=description?

#7981 [FLINK-11905][table-runtime-blink] Fix BlockCompressionTest does not compile with Java 9
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/compression/BlockCompressionTest.java
Labels: review=description?

#7961 [FLINK-11882][table-runtime-blink] Introduce BytesHashMap to batch hash agg
  flink-table/flink-table-runtime-blink/pom.xml
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/aggregate/BytesHashMap.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/aggregate/BytesHashMapSpillMemorySegmentPool.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/aggregate/BytesHashMapTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/aggregate/HashAggTest.java
  flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/aggregate/SumHashAggTestOperator.java
Labels: review=description?

#7989 [hotfix] Deduplicate the common codes in RecordWriterTest
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterTest.java
Labels: review=description?

#7896 [FLINK-9007] [kinesis] [e2e] Add Kinesis end-to-end test
  flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExample.java
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExampleTest.java
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisPubsubClient.java
  flink-end-to-end-tests/pom.xml
  flink-end-to-end-tests/run-pre-commit-tests.sh
  flink-end-to-end-tests/test-scripts/common.sh
  flink-end-to-end-tests/test-scripts/test_streaming_kinesis.sh
Labels: review=description?

#8010 [FLINK-11946][table-planner-blink] Introduce ExecNode to blink planner
  flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/plan/nodes/exec/ExecNodeVisitor.java
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/exec/BatchExecNode.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/exec/ExecNode.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/exec/StreamExecNode.scala
Labels: component=API/TableSQL, review=description?

#8009 [FLINK-11966] [table-planner-blink] Add support for generating optimized logical plan for simple query(Project, Filter, Values and Union all)
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalValues.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/optimize/program/FlinkBatchProgram.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/optimize/program/FlinkStreamProgram.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/FlinkBatchRuleSets.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/FlinkStreamRuleSets.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/batch/BatchExecCalcRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/batch/BatchExecUnionRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/batch/BatchExecValuesRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/stream/StreamExecCalcRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/stream/StreamExecUnionRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/stream/StreamExecValuesRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/FlinkRelOptUtil.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/RelTreeWriterImpl.scala
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/batch/sql/CalcTest.xml
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/batch/sql/UnionTest.xml
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/batch/sql/ValuesTest.xml
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/stream/sql/CalcTest.xml
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/stream/sql/UnionTest.xml
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/plan/stream/sql/ValuesTest.xml
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/batch/sql/CalcTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/batch/sql/UnionTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/batch/sql/ValuesTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/stream/sql/CalcTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/stream/sql/UnionTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/stream/sql/ValuesTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/plan/util/pojos.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/util/TableTestBase.scala
Labels: component=API/TableSQL, review=description?

#7897 [FLINK-11817] Uses aggregate function in DataStream API Tutorial
  docs/tutorials/datastream_api.md
Labels: component=Documentation, review=approved ✅

#7968 [FLINK-11692] [Datadog Reporter] added proxy to datadog reporter
  docs/monitoring/metrics.md
  flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpClient.java
  flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java
  flink-metrics/flink-metrics-datadog/src/test/java/org/apache/flink/metrics/datadog/DatadogHttpClientTest.java
Labels: component=Runtime/Metrics, review=description?

#8013 Minor example typo fix
  docs/dev/batch/dataset_transformations.md
Labels: review=description?

#7952 [FLINK-11872][table-runtime-blink] update lz4 license file.
  flink-table/flink-table-runtime-blink/pom.xml
  flink-table/flink-table-runtime-blink/src/main/resources/META-INF/NOTICE
Labels: component=BuildSystem, review=approved ✅

#7934 [FLINK-11853] [rest] Minimal implementation of POST for /jars/:jarid/plan
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/WebSubmissionExtension.java
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/AbstractJarPlanHeaders.java
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarPlanGetHeaders.java
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarPlanPostHeaders.java
  flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarPlanHandlerParameterTest.java
  flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarSubmissionITCase.java
Labels: component=Runtime/REST, review=approved ✅

#7800 [FLINK-11721][network] Remove IOMode from NetworkEnvironment
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskAsyncCallTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Labels: component=Runtime/Network, review=description?

#7767 [FLINK-11676][network] Make ResultPartitionWriter extend AutoCloseable
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/ResultPartitionWriter.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartition.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/AbstractCollectingResultPartitionWriter.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterTest.java
Labels: component=Runtime/Network, review=description?

#8014 [hostfix][docs]replace tabs with spaces in template code
  docs/dev/projectsetup/dependencies.md
Labels: review=description?

#7966 [FLINK-11887][metrics] Fixed latency metrics drift apart
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamSource.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
Labels: component=Runtime/Metrics, review=consensus?

#8028 [FLINK-11988][network] Remove legacy MockNetworkEnvironment
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/MockNetworkEnvironment.java
Labels: component=Runtime/Network, component=Tests, review=description?

#8031 [FLINK-9007] [kinesis] [e2e] Add Kinesis end-to-end test
  flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExample.java
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExampleTest.java
  flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisPubsubClient.java
  flink-end-to-end-tests/pom.xml
  flink-end-to-end-tests/run-pre-commit-tests.sh
  flink-end-to-end-tests/test-scripts/common.sh
  flink-end-to-end-tests/test-scripts/test_streaming_kinesis.sh
Labels: component=Connectors/Kinesis, component=Tests, review=description?

#8019 [FLINK-11981][table-planner-blink] Introduce ProjectionCodeGenerator and HashCodeGenerator for BaseRow
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/HashCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/ProjectionCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/codegen/HashCodeGeneratorTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/codegen/ProjectionCodeGeneratorTest.scala
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/util/HashUtil.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/GeneratedHashFunction.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/GeneratedProjection.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/HashFunction.java
Labels: component=SQL/Planner, review=description?

#8037 [FLINK-11907][types] Normalize String/BigInteger in GenericTypeInfoTest
  flink-tests/src/test/java/org/apache/flink/test/misc/GenericTypeInfoTest.java
Labels: component=API/TypeSerializationSystem, component=Tests, review=description?

#8035 [FLINK-11975][table-planner-blink] Support to run a sql query : 'SELECT * FROM (VALUES (1, 2, 3)) T(a, b, c)'
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/BatchTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/StreamTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/TableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/TableImpl.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/Types.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/StreamTableEnvironment.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/TableConversions.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/api/scala/package.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/FlinkTypeFactory.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/CodeGenUtils.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/InputFormatCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/SinkCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/ValuesCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/physical/batch/BatchExecSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/physical/batch/BatchExecValues.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/physical/stream/StreamExecSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/physical/stream/StreamExecValues.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/optimize/Optimizer.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/FlinkBatchRuleSets.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/FlinkStreamRuleSets.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/batch/BatchExecSinkRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/stream/StreamExecSinkRule.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/AppendStreamTableSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/BatchTableSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/CollectTableSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/DataStreamTableSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/RetractStreamTableSink.scala
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/sinks/UpsertStreamTableSink.scala
  flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/util/BaseRowUtil.java
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/batch/sql/ValuesITCase.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/stream/sql/ValuesITCase.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/utils/BatchTestBase.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/utils/StreamTestSink.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/utils/StreamingTestBase.scala
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/api/TableConfigOptions.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/GenericRow.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/GeneratedClass.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/values/ValuesInputFormat.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/BaseRowTypeInfo.java
Labels: component=TableSQL/Planner, review=description?

#7785 [FLINK-11707][network] Make InputGate extend AutoCloseable
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/InputGate.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGate.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NetworkEnvironmentTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientHandlerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/BarrierBufferMassiveRandomTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/MockInputGate.java
Labels: component=Runtime/Network, review=description?

#8059 [hotfix] Implement NoOpTaskActions to avoid mock in tests
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NoOpTaskActions.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NetworkEnvironmentTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientHandlerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/InputGateConcurrentTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/InputGateFairnessTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/TestSingleInputGate.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGateTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java
Labels: review=description?

#7762 [FLINK-11146] Remove invalid codes in ClusterClient
  flink-clients/src/main/java/org/apache/flink/client/LocalExecutor.java
  flink-clients/src/main/java/org/apache/flink/client/RemoteExecutor.java
  flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java
  flink-clients/src/main/java/org/apache/flink/client/program/ClusterClient.java
  flink-clients/src/main/java/org/apache/flink/client/program/ContextEnvironment.java
  flink-clients/src/main/java/org/apache/flink/client/program/MiniClusterClient.java
  flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
  flink-core/src/main/java/org/apache/flink/api/common/PlanExecutor.java
  flink-java/src/main/java/org/apache/flink/api/java/RemoteEnvironment.java
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/messages/GetClusterStatus.java
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/messages/GetClusterStatusResponse.java
  flink-scala-shell/src/test/java/org/apache/flink/api/java/FlinkILoopTest.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/util/FakeClusterClient.java
  flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
Labels: component=CommandLineClient, component=Tests, review=description?

#8043 [FLINK-11996] Remove the warning about case class maximum of 22 fields in the documentation
  docs/dev/types_serialization.md
Labels: component=API/Scala, component=API/TypeSerializationSystem, component=Documentation, review=approved ✅

#8072 [FLINK-12055][client] Remove legacy class ActorSystemLoader
  flink-clients/src/main/java/org/apache/flink/client/program/ActorSystemLoader.java
  flink-clients/src/main/java/org/apache/flink/client/program/DefaultActorSystemLoader.java
Labels: component=CommandLineClient, review=description?

#7807 [FLINK-11723][network] Remove KvState related components from Network…
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/KvStateService.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
  flink-runtime/src/main/scala/org/apache/flink/runtime/taskmanager/TaskManager.scala
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerServicesBuilder.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskAsyncCallTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/util/JvmExitOnFatalErrorTest.java
  flink-runtime/src/test/scala/org/apache/flink/runtime/testingUtils/TestingTaskManager.scala
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/InterruptSensitiveRestoreTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTerminationTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TaskCheckpointingBehaviourTest.java
Labels: component=Runtime/Network, review=description?

#8073 [FLINK-12057] Refactor MemoryLogger to accept termination future instead of ActorSystem
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/MemoryLogger.java
  flink-runtime/src/main/scala/org/apache/flink/runtime/taskmanager/TaskManager.scala
Labels: component=Runtime/Coordination, review=description?

#8071 [FLINK-12051][runtime][tests] Wait for TaskExecutor to be started
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
Labels: component=Tests, review=description?

#8063 [hotfix] Remove unused construction and IOMode from NetworkEnvironmentConfiguration
  flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/IOManager.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServicesConfiguration.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NetworkEnvironmentConfiguration.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/NetworkBufferCalculationTest.java
Labels: review=description?
