Repository apache/flink, pull requests merged in 2020-07, with the labels that each got.

#12795 [hotfix] Fix typo in TableConfig.java/hive_catalog.md/hive_catalog.zh.md
  docs/dev/table/hive/hive_catalog.md
  docs/dev/table/hive/hive_catalog.zh.md
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableConfig.java
Labels: review=description?

#12800 [hotfix] [docs] Fix typo ide setup
  docs/flinkDev/ide_setup.md
  docs/flinkDev/ide_setup.zh.md
Labels: review=description?

#12799 [FLINK-18455] Fix building Flink under Java > 11 versions
  pom.xml
Labels: component=BuildSystem, review=description?

#12801 [FLINK-16309][docs] ElasticSearch 7 connector is missing in SQL connector list
  docs/dev/table/connect.md
  docs/dev/table/connect.zh.md
Labels: component=Documentation, component=TableSQL/Ecosystem, review=description?

#12751 [FLINK-18336][checkpointing] Ignore failures of past checkpoints in CheckpointFailureManager
  flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
  flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManagerTest.java
Labels: review=description?

#12816 [hotfix] Add nohive classifier to orc-core in flink-sql-connector-hive:1.2.2 NOTICE file
  flink-connectors/flink-sql-connector-hive-1.2.2/src/main/resources/META-INF/NOTICE
Labels: review=description?

#12817 [FLINK-18471] Remove references to org.uncommons.maths in flink-runtime
  flink-runtime/pom.xml
  flink-runtime/src/main/resources/META-INF/NOTICE
Labels: review=description?

#12806 [FLINK-18462][table-planner-blink] Improve the exception message when INSERT INTO mismatch types for empty char
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/TableSchema.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/api/TableSchemaTest.java
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/sinks/TableSinkUtils.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/table/validation/LegacyTableSinkValidationTest.scala
Labels: component=TableSQL/Planner, review=description?

#12803 [FLINK-18461][table-planner-blink] Fix Changelog source can't be insert into upsert sink
  flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/BufferReduceStatementExecutor.java
  flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicOutputFormatBuilder.java
  flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSink.java
  flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataOutputFormat.java
  flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicOutputFormatTest.java
  flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSinkITCase.java
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/ChangelogSourceITCase.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSourceITCase.scala
Labels: component=TableSQL/Planner, review=description?

#12813 [FLINK-18470] Ensure rocksdb is loaded in RocksKeyGroupsRocksSingleStateIteratorTest
  flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksKeyGroupsRocksSingleStateIteratorTest.java
Labels: review=description?

#12802 [FLINK-18457][docs] Fix invalid links in "Detecting Patterns" page of "Streaming Concepts"
  docs/dev/table/streaming/match_recognize.md
Labels: component=Documentation, review=description?

#12778 [FLINK-18422][docs] Update Prefer tag in documentation 'Fault Tolerance training lesson'
  docs/learn-flink/fault_tolerance.md
  docs/learn-flink/fault_tolerance.zh.md
Labels: component=Documentation, component=Documentation/Training, review=description?

#12566 [FLINK-17761][connector/common] Add a constructor taking capacity as a parameter for `FutureCompletingBlockingQueue`
  flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/synchronization/FutureCompletingBlockingQueue.java
  flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/synchronization/FutureCompletingBlockingQueueTest.java
Labels: component=Connectors/Common, review=description?

#12825 [FLINK-18485] Update java to 8u251 in yarn docker kerberized test
  flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/Dockerfile
Labels: component=Deployment/YARN, review=description?

#12828 [FLINK-18173][docs] Update missing release notes for flink-json and flink-csv packaging
  docs/release-notes/flink-1.11.md
  docs/release-notes/flink-1.11.zh.md
Labels: component=BuildSystem, component=TableSQL/API, review=description?

#12797 [FLINK-18387] Translate "BlackHole SQL Connector" page into Chinese
  docs/dev/table/connectors/blackhole.zh.md
Labels: component=Documentation, component=TableSQL/Ecosystem, component=chinese-translation, review=description?

#12829 [FLINK-18501] Use inner class name for logging scheme mapping when pluggable fi…
  flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
  flink-core/src/main/java/org/apache/flink/core/fs/PluginFileSystemFactory.java
Labels: component=FileSystems, review=description?

#12830 [FLINK-18507][python] Move get_config implementation to TableEnvironment
  flink-python/pyflink/table/table_environment.py
Labels: component=API/Python, review=description?

#12831 [FLINK-18486][docs]add document for '%' module function.
  docs/dev/table/functions/systemFunctions.md
  docs/dev/table/functions/systemFunctions.zh.md
Labels: component=Documentation, component=TableSQL/API, review=description?

#12834 [hotfix] Update japicmp configuration for 1.11.0
  pom.xml
Labels: review=description?

#12832 Update japicmp configuration for 1.11.0
  pom.xml
Labels: review=description?

#12838 [FLINK-18514] Update groovy-all dependency to allow building under JDK 14
  flink-end-to-end-tests/pom.xml
Labels: component=<none>, review=description?

#12843 [hotfix][docs] Mark 1.9 as outdated
  docs/_config.yml
Labels: review=description?

#12842 [hotfix][docs] Mark 1.10 as outdated
  docs/_config.yml
Labels: review=description?

#12815 [FLINK-17075][coordination] Reconcile deployed Executions
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionDeploymentListener.java
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraphBuilder.java
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionStateUpdateListener.java
  flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/DefaultExecutionDeploymentReconciler.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/DefaultExecutionDeploymentTracker.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/ExecutionDeploymentReconciler.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/ExecutionDeploymentReconciliationHandler.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/ExecutionDeploymentTracker.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/factories/DefaultJobMasterServiceFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultSchedulerFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerNGFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/ExecutionDeploymentReport.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorToJobManagerHeartbeatPayload.java
  flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingExecutionGraphBuilder.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultExecutionDeploymentReconcilerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultExecutionDeploymentTrackerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterExecutionDeploymentReconciliationTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterPartitionReleaseTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/JobMasterBuilder.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java
  flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java
  flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/AllocationIdsExposingResourceManagerGateway.java
  flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerPartitionLifecycleTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorExecutionDeploymentReconciliationTest.java
Labels: component=Runtime/Coordination, review=description?

#12839 [FLINK-18501] Use inner class name for logging scheme mapping when fi…
  flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
  flink-core/src/main/java/org/apache/flink/core/fs/PluginFileSystemFactory.java
Labels: component=FileSystems, review=description?

#12840 [FLINK-18501] Use inner class name for logging scheme mapping when fi…
  flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
  flink-core/src/main/java/org/apache/flink/core/fs/PluginFileSystemFactory.java
Labels: component=FileSystems, review=description?

#12808 [FLINK-18458] Do not use property java.version
  flink-quickstart/flink-quickstart-java/src/main/resources/archetype-resources/pom.xml
  flink-walkthroughs/flink-walkthrough-datastream-java/src/main/resources/archetype-resources/pom.xml
  flink-walkthroughs/flink-walkthrough-table-java/src/main/resources/archetype-resources/pom.xml
  pom.xml
Labels: component=<none>, review=description?

#12560 [FLINK-18097][history-server] Cleaning job files in history server
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServerArchiveFetcher.java
  flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerTest.java
Labels: component=Runtime/WebFrontend, review=description?

#12769 [FLINK-15414] catch the right KafkaException for binding errors
  flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
Labels: component=Connectors/Kafka, component=Tests, review=description?

#12858 [FLINK-18534][kafka][table] Fix unstable KafkaTableITCase.testKafkaDebeziumChangelogSource
  flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
  flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
Labels: component=Connectors/Kafka, component=TableSQL/API, component=Tests, review=description?

#12720 [FLINK-18369] Fix instable TableEnvironmentITCase#testStatementSetWithSameSinkTableNames
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/runtime/batch/sql/TableEnvironmentITCase.scala
Labels: component=TableSQL/LegacyPlanner, review=description?

#12820 [FLINK-18434] Fix getter methods of AbstractJdbcCatalog
  flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java
  flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogITCase.java
Labels: component=TableSQL/Planner, review=description?

#12715 [FLINK-18361] Support username and password options for new Elasticse…
  docs/dev/table/connectors/elasticsearch.md
  docs/dev/table/connectors/elasticsearch.zh.md
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchConfiguration.java
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchOptions.java
  flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java
  flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactory.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactoryTest.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkTest.java
  flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSink.java
  flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactory.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactoryTest.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkTest.java
Labels: component=Connectors/ElasticSearch, review=description?

#12863 [FLINK-18539][datastream] Fix StreamExecutionEnvironment#addSource(SourceFunction, TypeInformation) doesn't use the user defined type information
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/StreamExecutionEnvironmentTest.java
Labels: component=API/DataStream, review=description?

#12877 [BP-1.11][FLINK-18539][datastream] Fix StreamExecutionEnvironment#addSource(SourceFunction, TypeInformation) doesn't use the user defined type information
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/StreamExecutionEnvironmentTest.java
Labels: component=API/DataStream, review=description?

#12878 [BP-1.10][FLINK-18539][datastream] Fix StreamExecutionEnvironment#addSource(SourceFunction, TypeInformation) doesn't use the user defined type information
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/StreamExecutionEnvironmentTest.java
Labels: component=API/DataStream, review=description?

#12885 [FLINK-18585][elasticsearch] Dynamic index can not work in new DynamicTableSink
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RowElasticsearchSinkFunction.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
Labels: component=Connectors/ElasticSearch, review=description?

#12886 [FLINK-18585][elasticsearch] Dynamic index can not work in new DynamicTableSink
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java
  flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RowElasticsearchSinkFunction.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
Labels: component=Connectors/ElasticSearch, review=description?

#12856 [FLINK-18529][hive] Query Hive table and filter by timestamp partitio…
  flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveTableUtil.java
  flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
Labels: component=Connectors/Hive, review=description?

#12896 [FLINK-18593][doc] Hive bundle jar URLs are broken
  docs/dev/table/hive/index.md
  docs/dev/table/hive/index.zh.md
Labels: review=description?

#12891 [FLINK-18591][metrics][documentation] Fix the format issue for metrics web page
  docs/monitoring/metrics.md
Labels: component=Documentation, component=Runtime/Metrics, review=description?

#12892 [FLINK-18591][metrics][documentation] Fix the format issue for metrics web page
  docs/monitoring/metrics.md
Labels: component=Documentation, component=Runtime/Metrics, review=description?

#12894 [BP-1.11][FLINK-18583][elasticsearch] Fix index id in ElasticSearch6 DynamicTableSink
  flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
Labels: component=Connectors/ElasticSearch, review=description?

#12890 [FLINK-18583] Fix index id in ElasticSearch6 DynamicTableSink
  flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java
  flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
  flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
Labels: component=Connectors/ElasticSearch, review=description?

#12898 [FLINK-17636][tests] Fix unstable test SingleInputGateTest#testConcurrentReadStateAndProcessAndClose
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
Labels: component=Runtime/Network, component=Tests, review=description?

#12879 [FLINK-17636][tests] Fix unstable test SingleInputGateTest#testConcur…
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
Labels: component=Runtime/Network, component=Tests, review=description?

#12897 [FLINK-18594][doc] The link is broken in kafka doc
  docs/dev/table/connectors/kafka.zh.md
Labels: component=Documentation, review=description?

#12827 [FLINK-18163][task] Add RecordWriter.volatileFlusherException
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/RecordWriter.java
Labels: component=Runtime/Task, review=description?

#12895 [hotfix][docs-zh] Fix invalid links in the page 'dev/table/streaming/match_recognize.zh.md'
  docs/dev/table/streaming/dynamic_tables.zh.md
  docs/dev/table/streaming/time_attributes.zh.md
Labels: review=description?

#12798 [FLINK-16087][docs-zh] Translate "Detecting Patterns" page of "Streaming Concepts" into Chinese
  docs/dev/table/streaming/match_recognize.zh.md
Labels: component=Documentation, component=chinese-translation, review=description?

#12888 [FLINK-18588] hive ddl create table support 'if not exists'
  flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
  flink-table/flink-sql-parser-hive/src/main/codegen/includes/parserImpls.ftl
  flink-table/flink-sql-parser-hive/src/main/java/org/apache/flink/sql/parser/hive/ddl/SqlCreateHiveTable.java
  flink-table/flink-sql-parser-hive/src/test/java/org/apache/flink/sql/parser/hive/FlinkHiveSqlParserImplTest.java
  flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTable.java
Labels: component=TableSQL/Planner, review=description?

#12925 [hotfix][doc] fix time duration unit in filesystem doc
  docs/dev/table/connectors/filesystem.md
  docs/dev/table/connectors/filesystem.zh.md
Labels: review=description?

#12927 [hotfix][doc] fix time duration unit in filesystem doc
  docs/dev/table/connectors/filesystem.md
  docs/dev/table/connectors/filesystem.zh.md
Labels: review=description?

#12918 [FLINK-18612][fs][local] Fix the issue when creating file under the current directory with relative path
  flink-core/src/main/java/org/apache/flink/core/fs/local/LocalFileSystem.java
  flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java
Labels: component=fs, review=description?

#12922 [FLINK-18612][fs][local] Fix the issue when creating file under the current directory with relative path
  flink-core/src/main/java/org/apache/flink/core/fs/local/LocalFileSystem.java
  flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java
Labels: component=fs, review=description?

#12937 [FLINK-18618] Use moby engine instead of docker-ce
  tools/azure-pipelines/jobs-template.yml
  tools/azure-pipelines/setup_docker.sh
Labels: component=BuildSystem/AzurePipelines, review=description?

#12930 [FLINK-18635][docs] Fix typo on website
  docs/concepts/timely-stream-processing.md
Labels: component=Documentation, review=description?

#12939 [FLINK-18644][doc][hive] Remove obsolete hive connector docs
  docs/dev/batch/connectors.md
  docs/dev/batch/connectors.zh.md
  docs/dev/table/hive/scala_shell_hive.md
  docs/dev/table/hive/scala_shell_hive.zh.md
Labels: component=Connectors/Hive, component=Documentation, review=description?

#12940 [FLINK-18644][doc][hive] Remove obsolete hive connector docs
  docs/dev/batch/connectors.md
  docs/dev/batch/connectors.zh.md
Labels: component=Connectors/Hive, component=Documentation, review=description?

#12936 [hotfix] Fix hypelink typo in connect.md and connect.zh.md
  docs/dev/table/connect.md
  docs/dev/table/connect.zh.md
Labels: review=description?

#12905 [FLINK-17789][API/Core] DelegatingConfiguration should remove prefix …
  flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java
  flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
Labels: component=API/Core, review=description?

#12953 [FLINK-18665][filesystem] Filesystem connector should use TableSchema exclude computed columns.
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/FileSystemITCaseBase.scala
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/FileSystemTableFactory.java
Labels: component=Connectors/FileSystem, component=TableSQL/Ecosystem, review=description?

#12954 [FLINK-18665][filesystem] Filesystem connector should use TableSchema exclude computed columns.
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/FileSystemITCaseBase.scala
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/FileSystemTableFactory.java
Labels: component=Connectors/FileSystem, component=TableSQL/Ecosystem, review=description?

#12867 [FLINK-18558][streaming] Introduce collect iterator with at least once semantics and exactly once semantics without fault tolerance
  docs/dev/table/sql/queries.md
  docs/dev/table/sql/queries.zh.md
  flink-python/pyflink/table/table_result.py
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamUtils.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/AbstractCollectResultBuffer.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CheckpointedCollectResultBuffer.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectResultFetcher.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectResultIterator.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/UncheckpointedCollectResultBuffer.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectResultBufferTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectResultIteratorTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunctionRandomITCase.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunctionTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/AbstractTestCoordinationRequestHandler.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/CollectSinkFunctionTestWrapper.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/CollectTestUtils.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/MockOperatorStateStore.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/TestCheckpointedCoordinationRequestHandler.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/TestUncheckpointedCoordinationRequestHandler.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableResult.java
  flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/sinks/SelectTableSinkBase.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/sinks/StreamSelectTableSink.java
Labels: component=API/DataStream, component=TableSQL/API, review=description?

#12923 [FLINK-18621][sql-client] Simplify the methods of Executor interface in sql client
  flink-core/src/main/java/org/apache/flink/util/CollectionUtil.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliResultViewTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutor.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutorBuilder.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/utils/TestTableResult.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/DependencyTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/TableEnvImpl.scala
Labels: component=TableSQL/Client, review=description?

#12721 [hotfix] Fix the table document errors
  docs/dev/table/streaming/dynamic_tables.md
  docs/dev/table/streaming/dynamic_tables.zh.md
  docs/dev/table/streaming/time_attributes.md
  docs/dev/table/streaming/time_attributes.zh.md
Labels: review=description?

#12960 [FLINK-18671][docs] Update upgrade compatibility table for 1.11.0
  docs/ops/upgrading.md
  docs/ops/upgrading.zh.md
Labels: component=Documentation, review=description?

#12963 [FLINK-18421][checkpointing] Fix logging of RejectedExecutionException logging
  flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Labels: component=Connectors/ElasticSearch, component=Tests, review=description?

#12864 [FLINK-18487][table] Datagen and Blackhole factory omits unrecognized properties silently
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/factories/BlackHoleTableSinkFactory.java
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/factories/DataGenTableSourceFactory.java
  flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/BlackHoleSinkFactoryTest.java
  flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
Labels: component=TableSQL/API, review=description?

#12976 [FLINK-18667][docs] Data types documentation misunderstand users
  docs/dev/table/types.md
  docs/dev/table/types.zh.md
Labels: component=Documentation, review=description?

#12934 [FLINK-18616][table sql/api]Add SHOW CURRENT DDLs
  docs/dev/table/hive/hive_dialect.md
  docs/dev/table/hive/hive_dialect.zh.md
  docs/dev/table/sql/show.md
  docs/dev/table/sql/show.zh.md
  flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCommandParser.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlCommandParserTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutorBuilder.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
  flink-table/flink-sql-parser-hive/src/main/codegen/data/Parser.tdd
  flink-table/flink-sql-parser-hive/src/main/codegen/includes/parserImpls.ftl
  flink-table/flink-sql-parser-hive/src/test/java/org/apache/flink/sql/parser/hive/FlinkHiveSqlParserImplTest.java
  flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
  flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
  flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowCurrentCatalog.java
  flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowCurrentDatabase.java
  flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowCurrentCatalogOperation.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowCurrentDatabaseOperation.java
  flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/calcite/FlinkPlannerImpl.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/sqlexec/SqlToOperationConverter.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/TableEnvImpl.scala
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/calcite/FlinkPlannerImpl.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/batch/BatchTableEnvironmentTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/catalog/CatalogTableITCase.scala
Labels: component=TableSQL/API, review=description?

#12955 [FLINK-18632][table-planner-blink] Assign row kind from input to outp…
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/SinkCodeGenerator.scala
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/StreamTableEnvironmentITCase.scala
Labels: component=TableSQL/Planner, review=description?

#12932 [FLINK-18638][runtime] FutureUtils support timeout message
  flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
Labels: component=<none>, review=description?

#12945 [FLINK-18629] Add type to ConnectedStreams#keyBy
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/ConnectedStreams.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/IterativeStream.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/api/DataStreamTest.java
  flink-streaming-scala/pom.xml
  flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/ConnectedStreams.scala
  flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/DataStreamUtils.scala
  flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/extensions/impl/acceptPartialFunctions/OnConnectedStream.scala
Labels: component=API/DataStream, review=description?

#12847 [FLINK-18521][release] Add script for creating snapshot branch
  tools/releasing/create_snapshot_branch.sh
Labels: component=ReleaseSystem, review=description?

#12977 [FLINK-18697][table-api] Add the missing test scope to the flink-streaming-java_2.11:test-jar dependency
  flink-table/flink-table-api-java-bridge/pom.xml
Labels: component=TableSQL/API, review=description?

#12561 [hotfix][docs]Fix typos in types_serialization.md and types_serializa…
  docs/dev/types_serialization.md
  docs/dev/types_serialization.zh.md
Labels: review=description?

#12941 [FLINK-18655][flink-runtime] Set failOnUnableToExtractRepoInfo to false for git-commit-id-plugin
  flink-runtime/pom.xml
Labels: component=Runtime/Configuration, review=description?

#12916 [FLINK-11547][flink-connector-kinesis] Fix JsonMappingException in DynamoDBStreamsSchema
  flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/serialization/DynamoDBStreamsSchema.java
Labels: component=Connectors/Kinesis, review=description?

#12952 [Hotfix] fix file event_driven.zh.md did't adding title anchor.
  docs/learn-flink/event_driven.zh.md
Labels: review=description?

#12873 [FLINK-18548][table-planner] Improve FlinkCalcMergeRule to merge calc nodes better
  flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkCalcMergeRule.scala
  flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/FlinkCalcMergeRuleTest.xml
  flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkCalcMergeRuleTest.scala
Labels: component=TableSQL/Planner, review=description?

#12997 [FLINK-18730][docs] Remove Beta tag from SQL Client docs
  docs/dev/table/sqlClient.md
  docs/dev/table/sqlClient.zh.md
Labels: component=Documentation, component=TableSQL/Client, review=description?

#12912 [FLINK-18595][network] Fix the deadlock issue by task thread and canceler thread in RemoteInputChannel
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
Labels: component=Runtime/Network, review=description?

#12989 [FLINK-18656][network,metrics] Fix startDelay metric for unaligned checkpoints
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/AlternatingCheckpointBarrierHandler.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierUnaligner.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/AlternatingCheckpointBarrierHandlerTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierUnalignerTest.java
Labels: component=Runtime/Metrics, component=Runtime/Network, review=description?

#13006 [FLINK-18595][network] Fix the deadlock of concurrently recycling buffer and releasing input channel
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
Labels: component=Runtime/Network, review=description?

#12968 [FLINK-18668][table-runtime-blink] BytesHashMap#growAndRehash should release newly allocated segments before throwing the exception
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesHashMap.java
  flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/LazyMemorySegmentPool.java
Labels: component=TableSQL/Runtime, review=description?

#13000 [FLINK-15467][task] Wait for sourceTaskThread to finish before exiting from StreamTask.invoke
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
Labels: component=Runtime/Task, review=description?

#13013 [FLINK-18595][network] Fix the deadlock of concurrently recycling buffer and releasing input channel
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
Labels: component=Runtime/Network, review=description?

#13022 [hotfix][docs] Update currentInputNWatermark metrics docs including N-ary operator
  docs/monitoring/metrics.md
  docs/monitoring/metrics.zh.md
Labels: review=description?

#12919 [FLINK-16048][avro] Support read/write confluent schema registry avro…
  flink-formats/flink-avro-confluent-registry/pom.xml
  flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/CachedSchemaCoderProvider.java
  flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/ConfluentRegistryAvroDeserializationSchema.java
  flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/ConfluentRegistryAvroSerializationSchema.java
  flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroFormatFactory.java
  flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroOptions.java
  flink-formats/flink-avro-confluent-registry/src/main/resources/META-INF/NOTICE
  flink-formats/flink-avro-confluent-registry/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroFormatFactoryTest.java
  flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroRowDataSeDeSchemaTest.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileSystemFormatFactory.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataSerializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroSerializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroToRowDataConverters.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RegistryAvroDeserializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RegistryAvroSerializationSchema.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RowDataToAvroConverters.java
  flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverter.java
  flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverterTest.java
Labels: component=Formats, component=TableSQL/Ecosystem, review=description?

#13035 [hotfix][csv][docs] Fix csv format option specification in docs.
  docs/dev/table/connectors/formats/csv.md
  docs/dev/table/connectors/formats/csv.zh.md
Labels: review=description?

#13036 [hotfix][csv][docs] Fix csv format option specification in docs.
  docs/dev/table/connectors/formats/csv.md
  docs/dev/table/connectors/formats/csv.zh.md
Labels: review=description?
