Repository apache/flink, pull requests merged in 2025-06, with the labels that each got.

#26627 [FLINK-37814][table-planner] Add FlinkRightJoinToLeftJoinRule
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkRightJoinToLeftJoinRule.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/FlinkRightJoinToLeftJoinRuleTest.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/FlinkRightJoinToLeftJoinRuleTest.xml
Labels: component=<none>

#26616 [FLINK-37875][table] Introduce key ordered async lookup join in planner
  docs/layouts/shortcodes/generated/execution_config_configuration.html
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLookupJoin.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLookupJoin.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLookupJoin.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/LookupJoinUtil.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/AsyncLookupOptionsTest.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/join/LookupJoinTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/LookupJoinTest.xml
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/join/LookupJoinTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/LookupJoinTest.scala
Labels: component=<none>

#26378 [FLINK-37536] [TABLE-SQL] Improve SQL Gateway documentation
  docs/content.zh/docs/dev/table/sql-gateway/overview.md
  docs/content.zh/docs/dev/table/sqlClient.md
  docs/content/docs/dev/table/sql-gateway/overview.md
  docs/content/docs/dev/table/sqlClient.md
Labels: component=Documentation

#26193 [hotfix][tests] Use Junit5 import in FileSinkTest.
  flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/FileSinkTest.java
Labels: stale

#26103 [FLINK-37249] Remove unnecessary --add-opens/--add-exports for java.base/sun.net.util
  docs/content.zh/docs/flinkDev/ide_setup.md
  docs/content/docs/flinkDev/ide_setup.md
  flink-dist/src/main/resources/config.yaml
  flink-dist/src/test/java/org/apache/flink/dist/BashJavaUtilsITCase.java
  flink-dist/src/test/resources/flink-conf.yaml
  pom.xml
Labels: component=BuildSystem

#26620 [FLINK-37851][state] Migrate state processor API from source API v1 to source API v2
  flink-architecture-tests/flink-architecture-tests-production/archunit-violations/e5126cae-f3fe-48aa-b6fb-60ae6cc3fcd5
  flink-core/src/main/java/org/apache/flink/api/connector/source/RichSourceReaderContext.java
  flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/input/OperatorStateInputFormat.java
  flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/input/SourceBuilder.java
  flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointDeepCopyTest.java
  flink-runtime/src/main/java/org/apache/flink/api/connector/source/lib/InputFormatSource.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
Labels: component=API/StateProcessor
