Repository apache/flink, pull requests merged in 2025-09, with the labels that each got.

#26958 [FLINK-38312][table] Add support for `SHOW MATERIALIZED TABLES`
  flink-python/pyflink/table/catalog.py
  flink-python/pyflink/table/table_environment.py
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/parser/SqlCommandParserImplTest.java
  flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
  flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
  flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowTables.java
  flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowViews.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalog.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowMaterializedTablesOperation.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowTablesConverter.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowViewsConverter.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkPlannerImpl.scala
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/UnknownCatalogTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlShowToOperationConverterTest.java
Labels: community-reviewed

#26811 [FLINK-38109] [flink-runtime] Fix BlobClient address when bindhost is set
  flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobCacheService.java
  flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
  flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobService.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherGateway.java
  flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
  flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobSubmitHandler.java
  flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobClientTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/TestingDispatcherGateway.java
Labels: community-reviewed

#26970 [hotfix][table] Fix incorrect state ttl setting in KeyedLookupJoinWrapper
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/KeyedLookupJoinWrapper.java
  flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/KeyedLookupJoinHarnessTest.java
Labels: community-reviewed

#26994 [FLINK-38365][table] Make invalid operations with `MATERIALIZED TABLE`s returning more user friendly message
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/TruncateTableOperation.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/utils/ValidationUtils.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConvertUtils.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlTruncateTableConverter.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
Labels: community-reviewed

#26987 [FLINK-38319][python] Allow TO_TIMESTAMP_LTZ to accept expression in PyFlink
  flink-python/pyflink/table/expressions.py
  flink-python/pyflink/table/tests/test_expression.py
Labels: community-reviewed

#26969 [BP-1.20][FLINK-37747][runtime] Use old subtask count for restored committable… #26546
  flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java
  flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2ITCase.java
Labels: community-reviewed, target:release-1.20

#27014 [release-2.0][FLINK-38370] Ensure CommitterOperator commits all pending committables in batch mode
  flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java
Labels: target:release-2.0

#27005 [FLINK-38379][table] Adjust visitMultiJoin in RelTimeIndicatorConverter to use fields and not rows
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RelTimeIndicatorConverter.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinSemanticTests.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinTestPrograms.java
Labels: community-reviewed

#27009 [FLINK-38386][build] Fix attaching type annotations for jdk23+
  flink-table/flink-sql-parser/pom.xml
  flink-table/flink-table-calcite-bridge/pom.xml
Labels: community-reviewed

#26546 [BP-2.0][FLINK-37747][runtime] Use old subtask count for restored committable…
  flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
  flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java
  flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2ITCase.java
Labels: component=<none>, target:release-2.0

#27051 [FLINK-38344][runtime-web] Fix the bug that The local files of the HistoryServer may risk never being deleted.
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServer.java
  flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerTest.java
Labels: target:release-2.1

#27052 [FLINK-38344][runtime-web] Fix the bug that The local files of the HistoryServer may risk never being deleted.
  flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServer.java
  flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerTest.java
Labels: target:release-1.20

#26924 [FLINK-38258][model] support model args in ptf and add ml_predict builtin ptf
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinition.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/ModelSemantics.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/CallContext.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInference.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInferenceUtil.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/MLPredictTypeStrategy.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/utils/CastCallContext.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/InputTypeStrategiesTestBase.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/TypeStrategiesTestBase.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/MLPredictInputTypeStrategyTest.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/MLPredictOutputTypeStrategyTest.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/utils/CallContextMock.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/utils/ModelSemanticsMock.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/utils/TableSemanticsMock.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/CallBindingCallContext.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/ml/SqlMLPredictTableFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalMLPredictTableFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalMLPredictTableFunctionRule.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalProcessTableFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalProcessTableFunctionRule.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestUtils.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/MLPredictTableFunctionTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MLPredictTableFunctionTest.xml
Labels: community-reviewed
