Repository apache/flink, pull requests merged in 2025-01, with the labels that each got.

#25854 [FLINK-36961][state/forst] Wait for the ForSt state executor to shutdown when disposing
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
Labels: component=<none>

#25563 [FLINK-36490][TABLE API] Remove the deprecated method in DataStreamScanProvider
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/source/DataStreamScanProvider.java
Labels: component=TableSQL/API

#25564 [FLINK-36491][TABLE API] Remove the deprecated method in DataStreamSinkProvider
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/sink/DataStreamSinkProvider.java
Labels: component=TableSQL/API

#25833 [FLINK-33117][table][docs] Fix scala example in udfs page
  docs/content.zh/docs/dev/table/functions/udfs.md
  docs/content/docs/dev/table/functions/udfs.md
Labels: component=Documentation

#25724 [FLINK-36758][sql-gateway] Introduce driver to load the application in application mode
  flink-core/src/main/java/org/apache/flink/util/FileUtils.java
  flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptRunner.java
  flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptRunnerITCase.java
  flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/MockHttpServer.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/application/SqlDriver.java
Labels: component=<none>

#25322 [FLINK-36269][python] Remove usage about TableEnvironmentInternal#fromTableSource in python module
  docs/content.zh/docs/dev/python/table/table_environment.md
  docs/content/docs/dev/python/table/table_environment.md
  flink-python/pyflink/table/table_environment.py
  flink-python/src/main/java/org/apache/flink/table/runtime/arrow/ArrowUtils.java
  flink-python/src/main/java/org/apache/flink/table/runtime/arrow/ByteArrayUtils.java
  flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSource.java
  flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSourceFactory.java
  flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSourceOptions.java
  flink-python/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
Labels: component=API/Python

#25529 [FLINK-36484] [TABLE-SQL] Remove deprecated methods StreamTableEnvironment#registerFunction
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/StreamTableEnvironment.java
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/internal/StreamTableEnvironmentImpl.java
  flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/StreamTableEnvironment.scala
  flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/internal/StreamTableEnvironmentImpl.scala
Labels: component=TableSQL/API

#25537 [FLINK-36500][table-common] Remove all deprecated methods in CallExpression
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/CallExpression.java
Labels: component=TableSQL/API

#25827 [BP-1.20][FLINK-34194] Update CI to Ubuntu 22.04 (Jammy)
  .github/workflows/docs.yml
  .github/workflows/template.flink-ci.yml
  .github/workflows/template.pre-compile-checks.yml
  azure-pipelines.yml
  tools/azure-pipelines/build-apache-repo.yml
  tools/azure-pipelines/build-nightly-dist.yml
  tools/azure-pipelines/build-python-wheels.yml
Labels: component=BuildSystem/CI

#25886 [FLINK-36593][runtime] Backport io.airlift:aircompressor upgrade to 0.27
  flink-runtime/pom.xml
  flink-runtime/src/main/resources/META-INF/NOTICE
Labels: component=API/Core

#25885 [FLINK-33571][table] Upgrade json-path from 2.7.0 to 2.9.0
  flink-table/flink-table-calcite-bridge/pom.xml
  flink-table/flink-table-runtime/src/main/resources/META-INF/NOTICE
  flink-table/pom.xml
Labels: component=<none>

#25887 [FLINK-36989][runtime] Fix scheduler benchmark regression caused by ConsumedSubpartitionContext
  flink-runtime/src/main/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContext.java
  flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/ConsumedPartitionGroup.java
  flink-runtime/src/test/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContextTest.java
Labels: component=Benchmarks

#25868 [FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java
Labels: component=Runtime/Coordination, component=Tests

#25818 [FLINK-36935][state/forst] Implement fast link for ForStFileSystem
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java
Labels: component=<none>

#25902 [BP-1.20][FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java
Labels: component=Runtime/Coordination, component=Tests

#25903 [BP-1.19][FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java
Labels: component=Runtime/Coordination, component=Tests

#25877 [FLINK-22091][yarn] Make Flink on YARN honor env.java.home
  docs/layouts/shortcodes/generated/environment_configuration.html
  flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
  flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
  flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/ContaineredTaskManagerParameters.java
  flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java
  flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
Labels: component=Runtime/Configuration

#25579 [FLINK-36501][table] Remove all deprecated methods in `CatalogFactory`
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogITCase.java
Labels: component=TableSQL/API

#25754 [FLINK-36760][sql-client] Supports to deploy script via sql client
  flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgramUtils.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CreateTableAsITCase.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/HdfsITCaseBase.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/PlannerScalaFreeITCase.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/SqlITCaseBase.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/UsingRemoteJarITCase.java
  flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/sql_client_remote_jar_e2e.sql
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/SqlClient.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptions.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptionsParser.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliUtils.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/DefaultContextUtils.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
  flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/SingleSessionManager.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
  flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
  flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/DefaultContext.java
  flink-table/flink-sql-jdbc-driver/src/test/java/org/apache/flink/table/jdbc/FlinkStatementTest.java
  flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/SQLJobSubmission.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/SqlYARNApplicationITCase.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
  flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterClientFactory.java
  flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Labels: component=TableSQL/Client

#25794 [BP-1.20][FLINK-36739] Update the NodeJS to v22.11.0 (LTS)
  flink-runtime-web/pom.xml
Labels: component=Runtime/WebFrontend

#25843 [FLINK-36950][table] Migrate WindowPropertiesRules to java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/WindowPropertiesRules.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/WindowPropertiesRule.scala
Labels: component=TableSQL/Planner

#25901 [FLINK-37010][Runtime] Unify KeyedProcessFunction and the async one
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/functions/AbstractAsyncStatefulRichFunction.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/functions/AsyncStatefulRichFunction.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/functions/DeclaringAsyncKeyedProcessFunction.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AsyncKeyedProcessOperator.java
  flink-streaming-java/src/test/java/org/apache/flink/asyncprocessing/operators/AsyncKeyedProcessOperatorTest.java
Labels: component=<none>

#25864 [FLINK-36968][table-planner] Deduplicate data with the same pk in values lookup table used for testing
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/LookupJoinITCase.scala
Labels: component=TableSQL/Planner

#25909 [FLINK-36507][table-common] Remove the deprecated method LogicalTypeParser#parse
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/descriptors/DescriptorProperties.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/legacy/descriptors/Schema.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeParser.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/LogicalTypeParserTest.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/utils/DataTypeFactoryMock.java
Labels: component=TableSQL/API

#25905 [FLINK-37016] ClusterEntrypoint can be closed before initialization
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
  flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java
Labels: component=Runtime/Coordination

#25527 [FLINK-36486] [TABLE SQL/API] Remove deprecated methods StreamTableEnvironment.registerDataStream from flink-table-api-java-bridge module
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/StreamTableEnvironment.java
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/internal/StreamTableEnvironmentImpl.java
  flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/StreamTableEnvironment.scala
  flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/internal/StreamTableEnvironmentImpl.scala
Labels: component=TableSQL/API

#25904 [FLINK-37014][doc] Fix examples in materialized table docs
  docs/content.zh/docs/dev/table/materialized-table/statements.md
  docs/content/docs/dev/table/materialized-table/statements.md
Labels: component=Documentation

#25917 [FLINK-37029][docs] Fix the materialized table docs of full mode cron expression
  docs/content.zh/docs/dev/table/materialized-table/overview.md
  docs/content.zh/docs/dev/table/materialized-table/quickstart.md
  docs/content.zh/docs/dev/table/materialized-table/statements.md
  docs/content/docs/dev/table/materialized-table/statements.md
Labels: component=Documentation

#25873 [FLINK-36941][docs] Update DATE_FORMAT Doc and Python Tests in 1.19
  docs/data/sql_functions.yml
  docs/data/sql_functions_zh.yml
  flink-python/pyflink/table/expressions.py
  flink-python/pyflink/table/tests/test_expression.py
Labels: component=Documentation

#25874 [FLINK-36941][docs] Update DATE_FORMAT Doc and Python Tests in 1.20
  docs/data/sql_functions.yml
  docs/data/sql_functions_zh.yml
  flink-python/pyflink/table/expressions.py
  flink-python/pyflink/table/tests/test_expression.py
Labels: component=Documentation

#25829 [BP-1.20][FLINK-36689][Runtime/Web Frontend] Update ng-zorro-antd to v18
  flink-runtime-web/README.md
  flink-runtime-web/web-dashboard/angular.json
  flink-runtime-web/web-dashboard/package-lock.json
  flink-runtime-web/web-dashboard/package.json
  flink-runtime-web/web-dashboard/src/app/app.component.html
  flink-runtime-web/web-dashboard/src/app/pages/job/modules/completed-job/cluster-config.guard.ts
  flink-runtime-web/web-dashboard/src/app/services/job.service.spec.ts
  flink-runtime-web/web-dashboard/src/main.ts
  flink-runtime-web/web-dashboard/tsconfig.json
Labels: component=Runtime/WebFrontend

#25813 [FLINK-36227] Restore compatibility with Logback 1.2
  flink-core/src/main/java/org/apache/flink/util/MdcUtils.java
  flink-core/src/test/java/org/apache/flink/util/MdcLogbackCompatibilityTest.java
Labels: component=API/Core

#25926 [BP-1.20][FLINK-37014][doc] Fix examples in materialized table docs
  docs/content.zh/docs/dev/table/materialized-table/statements.md
  docs/content/docs/dev/table/materialized-table/statements.md
Labels: component=Documentation

#25770 [FLINK-36871][runtime] add rescale metrics in scheduler
  docs/content.zh/docs/ops/metrics.md
  docs/content/docs/ops/metrics.md
  flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
  flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
  flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockRestartingContext.java
  flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
Labels: component=Runtime/Metrics

#25918 [FLINK-37030] Support lazy initialization for state serializer in State V2
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AggregatingStateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStore.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ListStateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/MapStateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ReducingStateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptorUtils.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateSerializerReference.java
  flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ValueStateDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateDescriptorTest.java
  flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStListStateTest.java
Labels: component=Runtime/StateBackends

#25931 [FLINK-37082][table-planner] Disable adaptive join optimization when enable batch job progress recovery.
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/AdaptiveJoinProcessor.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.scala
Labels: component=TableSQL/Planner

#25923 [1.19][FLINK-37016] ClusterEntrypoint can be closed before initialization
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
  flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java
Labels: component=Runtime/Coordination

#25922 [1.20][FLINK-37016] ClusterEntrypoint can be closed before initialization
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
  flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java
Labels: component=Runtime/Coordination

#25928 [FLINK-36707][table] Integrate PTF type inference into Calcite
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionResultTemplate.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/TypeInferenceExtractor.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/CallContext.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/DefaultStateTypeStrategy.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StateTypeStrategy.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInference.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInferenceUtil.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/utils/AdaptedCallContext.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
  flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/ProcedureNamespace.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkSqlCallBinding.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/FunctionCatalogOperatorTable.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/bridging/BridgingSqlAggFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/bridging/BridgingSqlFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/bridging/BridgingUtils.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/CallBindingCallContext.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/OperatorBindingCallContext.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceOperandChecker.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceOperandInference.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/ProcedureITCase.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/common/ViewsExpandingTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/operator/StreamOperatorNameTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/CalcPythonCorrelateTransposeRuleTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PythonCorrelateSplitRuleTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/SplitPythonConditionFromCorrelateRuleTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MiniBatchIntervalInferTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalFunctionJoinTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/table/CorrelateTest.xml
Labels: component=TableSQL/Planner, component=TableSQL/API

#25830 [BP-1.20][FLINK-36740] [WebFrontend] Update frontend dependencies to address vulnerabilities
  flink-runtime-web/README.md
  flink-runtime-web/src/main/resources/META-INF/NOTICE
  flink-runtime-web/web-dashboard/.eslintrc.js
  flink-runtime-web/web-dashboard/dev/generate_notice.sh
  flink-runtime-web/web-dashboard/dev/notice-template
  flink-runtime-web/web-dashboard/package-lock.json
  flink-runtime-web/web-dashboard/package.json
  flink-runtime-web/web-dashboard/src/app/pages/overview/statistic/overview-statistic.component.html
  pom.xml
Labels: component=Runtime/WebFrontend

#25832 [FLINK-36946][Metrics] Optimize sink operator name truncate
  flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
  flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/JobManagerJobMetricGroup.java
  flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroup.java
  flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
  flink-runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
  flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java
  flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java
Labels: component=Runtime/Metrics

#25943 [FLINK-37085][table-planner] fix ut in AdaptiveJoinTest.testAdaptiveJoinWithBatchJobRecovery.
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml
Labels: component=BuildSystem/CI

#25915 [FLINK-37024][task] Make cancel watchdog cover tasks stuck in DEPLOYING state
  flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
  flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
Labels: component=Runtime/Task

#25935 [FLINK-37025] Fix generating watermarks in SQL on-periodic (#25921)
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/WatermarkITCase.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/GeneratedWatermarkGeneratorSupplier.java
Labels: component=TableSQL/Runtime

#25942 [FLINK-36227] Restore compatibility with Logback 1.2 - Flink 2.0
  flink-core/src/main/java/org/apache/flink/util/MdcUtils.java
  flink-core/src/test/java/org/apache/flink/util/MdcLogbackCompatibilityTest.java
Labels: component=API/Core

#25906 [FLINK-37019][tests] Bump junit5 to 5.11.4
  flink-runtime/pom.xml
  flink-table/flink-sql-gateway/pom.xml
  flink-table/flink-sql-parser/pom.xml
  flink-table/flink-table-planner/pom.xml
  flink-yarn-tests/pom.xml
  pom.xml
Labels: component=Tests, component=TestInfrastructure

#25763 [FLINK-36862][table] Implement additional TO_TIMESTAMP_LTZ() functions
  docs/data/sql_functions.yml
  docs/data/sql_functions_zh.yml
  flink-python/pyflink/table/expressions.py
  flink-python/pyflink/table/tests/test_expression.py
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
  flink-table/flink-table-api-scala/src/main/scala/org/apache/flink/table/api/ImplicitExpressionConversions.scala
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ToTimestampLtzTypeStrategy.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ToTimestampLtzTypeStrategyTest.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/StringCallGen.scala
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/TimeFunctionsITCase.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/batch/sql/TimeTravelTest.java
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ToTimestampLtzFunction.java
Labels: component=<none>

#25936 [FLINK-37083][e2e] Fix failed SqlYARNApplicationITCase on AZP
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/SqlYARNApplicationITCase.java
Labels: component=BuildSystem/CI

#25947 [FLINK-37091][table-common] Remove deprecated interface CatalogLock
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogLock.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/RequireCatalogLock.java
Labels: component=TableSQL/API

#25784 [FLINK-36761][docs] Add document about how to use SQL Gateway and SQL Client to deploy script
  docs/content.zh/docs/dev/table/sql-gateway/overview.md
  docs/content.zh/docs/dev/table/sql-gateway/rest.md
  docs/content.zh/docs/dev/table/sqlClient.md
  docs/content/docs/dev/table/sql-gateway/overview.md
  docs/content/docs/dev/table/sql-gateway/rest.md
  docs/content/docs/dev/table/sqlClient.md
  docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
  docs/layouts/shortcodes/generated/rest_v4_sql_gateway.html
  docs/static/generated/rest_v1_dispatcher.yml
  docs/static/generated/rest_v4_sql_gateway.yml
Labels: component=Documentation

#25941 [1.19][FLINK-34194][ci] Updates test CI container to be based on Ubuntu 22.04
  .github/workflows/docs.yml
  .github/workflows/template.flink-ci.yml
  .github/workflows/template.pre-compile-checks.yml
  azure-pipelines.yml
  tools/azure-pipelines/build-apache-repo.yml
  tools/azure-pipelines/build-nightly-dist.yml
  tools/azure-pipelines/build-python-wheels.yml
Labels: component=BuildSystem/CI

#25940 [FLINK-35721][docs] Fix CAST compatibility table
  docs/content/docs/dev/table/types.md
Labels: component=Documentation, component=TableSQL/Planner

#25971 [FLINK-35512][tests] Do not depend on the `flink-clients` jar in `ArtifactFetchManagerTest`
  flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java
  flink-core/src/test/java/org/apache/flink/testutils/TestingUtils.java
Labels: component=<none>

#25969 [BP-1.19][FLINK-35512][tests] Do not depend on the `flink-clients` jar in `ArtifactFetchManagerTest`
  flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java
Labels: component=<none>

#25960 [FLINK-37101] Remove legacy internal methods for changing serializer behavior in SerializerConfig
  flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/stream/PartitionCommitInfoTest.java
  flink-core/src/main/java/org/apache/flink/api/common/serialization/SerializerConfig.java
  flink-core/src/main/java/org/apache/flink/api/common/serialization/SerializerConfigImpl.java
  flink-core/src/test/java/org/apache/flink/api/common/ExecutionConfigFromConfigurationTest.java
  flink-core/src/test/java/org/apache/flink/api/common/ExecutionConfigTest.java
  flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroKryoSerializerRegistrationsTest.java
  flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroTypeExtractionTest.java
  flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/types/PojoTestUtils.java
Labels: component=API/TypeSerializationSystem

#25869 [FLINK-36310] Remove per-job mode
  docs/content.zh/docs/concepts/flink-architecture.md
  docs/content.zh/docs/deployment/cli.md
  docs/content.zh/docs/deployment/overview.md
  docs/content.zh/docs/deployment/resource-providers/native_kubernetes.md
  docs/content.zh/docs/deployment/resource-providers/standalone/kubernetes.md
  docs/content.zh/docs/deployment/resource-providers/yarn.md
  docs/content.zh/docs/ops/debugging/debugging_classloading.md
  docs/content/docs/concepts/flink-architecture.md
  docs/content/docs/deployment/cli.md
  docs/content/docs/deployment/overview.md
  docs/content/docs/deployment/resource-providers/yarn.md
  docs/content/docs/ops/debugging/debugging_classloading.md
  docs/layouts/shortcodes/generated/deployment_configuration.html
  docs/static/fig/deployment_modes.svg
  flink-clients/src/main/java/org/apache/flink/client/cli/GenericCLI.java
  flink-clients/src/main/java/org/apache/flink/client/deployment/ClusterDescriptor.java
  flink-clients/src/main/java/org/apache/flink/client/deployment/StandaloneClusterDescriptor.java
  flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractJobClusterExecutor.java
  flink-clients/src/test/java/org/apache/flink/client/cli/util/DummyClusterDescriptor.java
  flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java
  flink-end-to-end-tests/run-nightly-tests.sh
  flink-end-to-end-tests/test-scripts/test_pyflink_yarn.sh
  flink-end-to-end-tests/test-scripts/test_yarn_job_kerberos_docker.sh
  flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobDispatcherFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcess.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactoryFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/JobClusterEntrypoint.java
  flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/component/DefaultDispatcherResourceManagerComponentFactory.java
  flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/MiniDispatcherRestEndpoint.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/JobDispatcherITCase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactoryFactoryTest.java
  flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/DeployScriptITCase.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNFileReplicationITCase.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNITCase.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
  flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnConfigurationITCase.java
  flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  flink-yarn/src/main/java/org/apache/flink/yarn/cli/AbstractYarnCli.java
  flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
  flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnDeploymentTarget.java
  flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnEntrypointUtils.java
  flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnJobClusterEntrypoint.java
  flink-yarn/src/main/java/org/apache/flink/yarn/executors/YarnJobClusterExecutor.java
  flink-yarn/src/main/java/org/apache/flink/yarn/executors/YarnJobClusterExecutorFactory.java
  flink-yarn/src/main/resources/META-INF/services/org.apache.flink.core.execution.PipelineExecutorFactory
  flink-yarn/src/test/java/org/apache/flink/yarn/FlinkYarnSessionCliTest.java
  flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterClientFactoryTest.java
  flink-yarn/src/test/java/org/apache/flink/yarn/entrypoint/YarnJobClusterEntrypointTest.java
Labels: component=<none>

#25848 [FLINK-36957][Datastream] Implement asyc state version of stream flatmap
  flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/KeyedStateInputFormatTest.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AsyncStreamFlatMap.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
Labels: component=<none>

#25884 [FLINK-36899][state/forst] Introduce metrics for forst cache
  docs/content.zh/docs/ops/metrics.md
  docs/content/docs/ops/metrics.md
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/BundledCacheLimitPolicy.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CacheLimitPolicy.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileBasedCache.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SizeBasedCacheLimitPolicy.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SpaceBasedCacheLimitPolicy.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStExtension.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java
Labels: component=<none>

#25950 [FLINK-36506][table] Remove all deprecated methods in ColumnStats
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/plan/stats/ColumnStats.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdColumnInterval.scala
Labels: component=TableSQL/API

#25973 [FLINK-37108] Use-non terminal savepoint in source/sink suite
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java
Labels: component=<none>

#25974 [FLINK-37108] Use-non terminal savepoint in source/sink suite [1.20]
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java
Labels: component=<none>

#25953 [FLINK-37026] Add Stale PR GitHub Action workflow
  .github/workflows/stale.yml
Labels: component=<none>

#25972 [FLINK-36707][table] Add output strategy to SystemTypeInference
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
  flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/ProcedureNamespace.java
  flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkSqlCallBinding.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/bridging/BridgingSqlFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceReturnInference.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlDefaultOperator.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java
Labels: component=TableSQL/Planner, component=TableSQL/API

#25958 [1.19][FLINK-36689][Runtime/Web Frontend] Update ng-zorro-antd to v18
  flink-runtime-web/README.md
  flink-runtime-web/web-dashboard/angular.json
  flink-runtime-web/web-dashboard/package-lock.json
  flink-runtime-web/web-dashboard/package.json
  flink-runtime-web/web-dashboard/src/app/app.component.html
  flink-runtime-web/web-dashboard/src/app/pages/job/modules/completed-job/cluster-config.guard.ts
  flink-runtime-web/web-dashboard/src/app/services/job.service.spec.ts
  flink-runtime-web/web-dashboard/src/main.ts
  flink-runtime-web/web-dashboard/tsconfig.json
Labels: component=Runtime/WebFrontend

#25975 [FLINK-37108] Use-non terminal savepoint in source/sink suite [1.19]
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
  flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java
Labels: component=<none>

#25945 [FLINK-37015][doc] Remove Scala contents in serialization doc
  docs/content/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md
  docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
Labels: component=Documentation

#25566 [FLINK-36493][TABLE API] Remove all deprecated methods in MapView
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/dataview/MapView.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/dataview/MapViewTypeInfoFactory.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/typeutils/LegacyDataViewUtils.scala
Labels: component=TableSQL/API

#25565 [FLINK-36492][TABLE API] Remove all deprecated methods in ListView
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/dataview/ListView.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/dataview/ListViewTypeInfoFactory.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/typeutils/LegacyDataViewUtils.scala
Labels: component=TableSQL/API

#25981 [FLINK-36496][table] Remove deprecated method CatalogFunction#isGeneric
  flink-python/docs/reference/pyflink.table/catalog.rst
  flink-python/pyflink/table/catalog.py
  flink-python/pyflink/table/tests/test_catalog.py
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogFunctionImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogFunction.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/CatalogTest.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/functions/UserDefinedFunctionHelperTest.java
Labels: component=TableSQL/API

#25979 [FLINK-36503][table] Remove deprecated method FunctionDefinitionFactory#createFunctionDefinition
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FunctionDefinitionFactory.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestFunctionDefinitionFactory.java
Labels: component=TableSQL/API

#25967 [FLINK-36499][table]Remove deprecated method `SupportsProjectionPushDown#applyProjection`
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsProjectionPushDown.java
Labels: component=TableSQL/API

#25963 [FLINK-36504][table]Remove all deprecated methods ModuleFactory
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/ModuleFactory.java
  flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/module/LegacyDummyModuleFactory.java
  flink-table/flink-table-common/src/test/resources/META-INF/services/org.apache.flink.table.legacy.factories.TableFactory
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
Labels: component=TableSQL/API

#25959 [1.19][FLINK-36740] [WebFrontend] Update frontend dependencies to address vulnerabilities
  flink-runtime-web/README.md
  flink-runtime-web/src/main/resources/META-INF/NOTICE
  flink-runtime-web/web-dashboard/.eslintrc.js
  flink-runtime-web/web-dashboard/dev/generate_notice.sh
  flink-runtime-web/web-dashboard/dev/notice-template
  flink-runtime-web/web-dashboard/package-lock.json
  flink-runtime-web/web-dashboard/package.json
  flink-runtime-web/web-dashboard/src/app/pages/overview/statistic/overview-statistic.component.html
  pom.xml
Labels: component=Runtime/WebFrontend

#25898 [FLINK-36181] Use Java 17 by default
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/template.flink-ci.yml
  .github/workflows/template.pre-compile-checks.yml
  README.md
  azure-pipelines.yml
  flink-dist-scala/src/main/resources/META-INF/NOTICE
  flink-end-to-end-tests/test-scripts/common_docker.sh
  flink-rpc/flink-rpc-akka/pom.xml
  flink-table/flink-table-planner-loader-bundle/src/main/resources/META-INF/NOTICE
  pom.xml
  tools/azure-pipelines/build-apache-repo.yml
Labels: component=BuildSystem, component=BuildSystem/AzurePipelines, component=BuildSystem/CI

#25992 [FLINK-37026] Fix the stale pr message formatting
  .github/workflows/stale.yml
Labels: component=<none>

#25990 [FLINK-37137][runtime] Fix unstable test testGenerateStreamGraphJson
  flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonGeneratorTest.java
Labels: component=BuildSystem/CI

#25954 [FLINK-37090][e2e] Add adaptive broadcast join to e2e tpc-ds tests.
  flink-end-to-end-tests/test-scripts/test_tpcds.sh
Labels: component=<none>

#25989 [FLINK-37139][table-planner] Improve AdaptiveSkewedJoinOptimizationStrategy to make it effective in more scenarios
  flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamEdge.java
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveSkewedJoinITCase.scala
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveSkewedJoinOptimizationStrategy.java
Labels: component=Runtime/Coordination

#25986 [FLINK-32647][pyflink] Support create catalog in pyflink table environment
  flink-python/docs/reference/pyflink.table/catalog.rst
  flink-python/docs/reference/pyflink.table/table_environment.rst
  flink-python/pyflink/table/__init__.py
  flink-python/pyflink/table/catalog.py
  flink-python/pyflink/table/table_environment.py
  flink-python/pyflink/table/tests/test_environment_completeness.py
  flink-python/pyflink/table/tests/test_table_environment_api.py
Labels: component=API/Python

#25373 [FLINK-36293][state] make sure register is closed before verification in testAsyncCancellation
  flink-core/src/main/java/org/apache/flink/util/AbstractAutoCloseableRegistry.java
  flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/RocksDBWriteBatchWrapperTest.java
Labels: component=Runtime/StateBackends

#25952 [FLINK-37098] Fix selecting time attribute from a view
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/CatalogManagerMocks.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/ParserMock.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Column.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/QueryOperationCatalogViewTable.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/SqlCatalogViewTable.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversionTestBase.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/PlannerMocks.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/analyze/NonDeterministicUpdateAnalyzerTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/common/ViewsExpandingTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml
Labels: component=TableSQL/Planner

#25889 [FLINK-37001][table] Remove code related to registerTableSinkInternal in tests and remove this method in TableEnvironmentInternal
  flink-end-to-end-tests/flink-tpcds-test/pom.xml
  flink-end-to-end-tests/flink-tpcds-test/src/main/java/org/apache/flink/table/tpcds/TpcdsTestProgram.java
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/sinks/LegacyCsvDynamicTableSinkFactory.java
  flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/sinks/LegacyCsvDynamicTableSinkOptions.java
  flink-table/flink-table-api-java-bridge/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentInternal.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/sinks/CollectTableSink.scala
  flink-table/flink-table-planner/src/test/resources/explain/testFromToDataStreamAndSqlUpdate.out
  flink-table/flink-table-planner/src/test/resources/explain/testFromToDataStreamAndSqlUpdateWithPlanAdvice.out
  flink-table/flink-table-planner/src/test/resources/explain/testSqlUpdateAndToDataStream.out
  flink-table/flink-table-planner/src/test/resources/explain/testSqlUpdateAndToDataStreamWithPlanAdvice.out
  flink-table/flink-table-planner/src/test/resources/explain/testStatementSet.out
  flink-table/flink-table-planner/src/test/resources/explain/testStatementSetExecutionExplain.out
  flink-table/flink-table-planner/src/test/resources/explain/testStatementSetWithPlanAdvice.out
  flink-table/flink-table-planner/src/test/resources/explain/testStreamTableEnvironmentExecutionExplain.out
  flink-table/flink-table-planner/src/test/resources/explain/testStreamTableEnvironmentExplain.out
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/api/batch/ExplainTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/api/stream/ExplainTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/DagOptimizationTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/LegacySinkTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DagOptimizationTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/LegacySinkTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MiniBatchIntervalInferTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/RelTimeIndicatorConverterTest.xml
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/batch/ExplainTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/stream/ExplainTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/DagOptimizationTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/LegacySinkTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/DagOptimizationTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/LegacySinkTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/MiniBatchIntervalInferTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/RelTimeIndicatorConverterTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/table/validation/LegacyTableSinkValidationTest.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/LegacyTableSinkITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CalcITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CorrelateITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/GroupWindowITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/Limit0RemoveITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/RankITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/UnnestITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/AggregateITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/JoinITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/LegacyTableSinkITCase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/TestSinkUtil.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/MemoryTableSourceSinkUtil.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
  flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/testTableSourceSinks.scala
Labels: component=TableSQL/API

#25993 [FLINK-37140][runtime] Create async timer service when restore async operator
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImpl.java
  flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
  flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
  flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/MailboxWatermarkProcessorTest.java
Labels: component=<none>

#26002 [FLINK-37098] Fix selecting time attribute from a view
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/CatalogManagerMocks.java
  flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/ParserMock.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Column.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/QueryOperationCatalogViewTable.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/SqlCatalogViewTable.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversionTestBase.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/PlannerMocks.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/analyze/NonDeterministicUpdateAnalyzerTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/common/ViewsExpandingTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml
Labels: component=TableSQL/Planner

#25646 [FLINK-36695][Formats] Bump Parquet dependency to 1.14.4
  flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
  flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
  flink-formats/pom.xml
  flink-python/pom.xml
  flink-python/src/main/resources/META-INF/NOTICE
Labels: component=Formats

#26004 [FLINK-37084][python] fix TimerRegistration concurrency bug in pyflink
  flink-python/src/main/java/org/apache/flink/python/PythonFunctionRunner.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/AbstractPythonFunctionOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/AbstractExternalPythonFunctionOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/ExternalPythonCoProcessOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/ExternalPythonKeyedCoProcessOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/ExternalPythonKeyedProcessOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/ExternalPythonProcessOperator.java
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/timer/TimerRegistrationAction.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamDataStreamPythonFunctionRunner.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamPythonFunctionRunner.java
  flink-python/src/main/java/org/apache/flink/table/runtime/operators/python/AbstractStatelessFunctionOperator.java
  flink-python/src/main/java/org/apache/flink/table/runtime/operators/python/aggregate/AbstractPythonStreamAggregateOperator.java
  flink-python/src/main/java/org/apache/flink/table/runtime/runners/python/beam/BeamTablePythonFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/PassThroughPythonStreamGroupWindowAggregateOperator.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/PythonStreamGroupAggregateOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/PythonStreamGroupTableAggregateOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/batch/BatchArrowPythonGroupAggregateFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/batch/BatchArrowPythonGroupWindowAggregateFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/batch/BatchArrowPythonOverWindowAggregateFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/stream/StreamArrowPythonGroupWindowAggregateFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/stream/StreamArrowPythonProcTimeBoundedRangeOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/stream/StreamArrowPythonProcTimeBoundedRowsOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/stream/StreamArrowPythonRowTimeBoundedRangeOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/aggregate/arrow/stream/StreamArrowPythonRowTimeBoundedRowsOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/scalar/PythonScalarFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/scalar/arrow/ArrowPythonScalarFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/operators/python/table/PythonTableFunctionOperatorTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonAggregateFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonScalarFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonTableFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamAggregatePythonFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamGroupWindowAggregatePythonFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamTableAggregatePythonFunctionRunner.java
Labels: component=API/Python

#26005 [FLINK-37164][Runtime] Speed up state v2 synchronous methods execution
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateExecutor.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequest.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java
  flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/MockStateExecutor.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
Labels: component=<none>

#25998 [FLINK-35405][runtime] Add metrics for AsyncExecutionController
  docs/content.zh/docs/ops/metrics.md
  docs/content/docs/ops/metrics.md
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
  flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
  flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
  flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateBackendTestV2Base.java
  flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateTestBase.java
Labels: component=<none>

#26006 [FLINK-37021][state/forst] Make Forst remote dir share with checkpoint
  flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorageAccess.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
  flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendV2Test.java
Labels: component=<none>

#25541 [FLINK-35282][python] Upgrade Apache Beam > 2.54
  docs/content.zh/docs/deployment/cli.md
  docs/content.zh/docs/dev/table/sqlClient.md
  docs/content/docs/deployment/cli.md
  docs/content/docs/dev/table/sqlClient.md
  docs/layouts/shortcodes/generated/python_configuration.html
  flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java
  flink-python/README.md
  flink-python/dev/dev-requirements.txt
  flink-python/pom.xml
  flink-python/pyflink/datastream/stream_execution_environment.py
  flink-python/pyflink/fn_execution/beam/beam_operations_slow.py
  flink-python/pyflink/fn_execution/beam/beam_worker_pool_service.py
  flink-python/pyflink/table/table_config.py
  flink-python/pyflink/table/tests/test_pandas_conversion.py
  flink-python/pyproject.toml
  flink-python/setup.py
  flink-python/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java
  flink-python/src/main/java/org/apache/beam/runners/fnexecution/state/GrpcStateService.java
  flink-python/src/main/java/org/apache/beam/sdk/fn/server/ServerFactory.java
  flink-python/src/main/java/org/apache/beam/vendor/grpc/v1p60p1/io/grpc/internal/SharedResourceHolder.java
  flink-python/src/main/java/org/apache/flink/python/PythonOptions.java
  flink-python/src/main/java/org/apache/flink/python/metric/process/FlinkMetricContainer.java
  flink-python/src/main/java/org/apache/flink/python/util/ProtoUtils.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamDataStreamPythonFunctionRunner.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamPythonFunctionRunner.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/state/BeamBagStateHandler.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/state/BeamMapStateHandler.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/state/BeamStateRequestHandler.java
  flink-python/src/main/java/org/apache/flink/table/runtime/runners/python/beam/BeamTablePythonFunctionRunner.java
  flink-python/src/main/resources/META-INF/NOTICE
  flink-python/src/test/java/org/apache/flink/python/metric/process/FlinkMetricContainerTest.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonAggregateFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonScalarFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughPythonTableFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamAggregatePythonFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamGroupWindowAggregatePythonFunctionRunner.java
  flink-python/src/test/java/org/apache/flink/table/runtime/utils/PassThroughStreamTableAggregatePythonFunctionRunner.java
  flink-table/flink-sql-client/src/test/resources/cli/all-mode-help.out
  flink-table/flink-sql-client/src/test/resources/cli/embedded-mode-help.out
  pom.xml
Labels: component=API/Python

#26011 [FLINK-37168][python] clean up TimerRegistrationAction in unregisteredTimers list after timers are registered
  flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/timer/TimerRegistrationAction.java
  flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamPythonFunctionRunner.java
Labels: component=API/Python

#26014 [FLINK-37172][table-runtime] Add logs in all existing async state ops to check if they are under async state when running
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/async/AsyncStateGroupAggFunction.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/asyncwindow/processors/AbstractAsyncStateSliceWindowAggProcessor.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateDeduplicateFunctionBase.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/AsyncStateStreamingJoinOperator.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/window/asyncprocessing/AsyncStateWindowJoinOperator.java
  flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AbstractAsyncStateTopNFunction.java
Labels: component=TableSQL/Runtime

#26018 [FLINK-37174][sql-client] Fix failed tests about SqlClientTest#testPrintAllModeHelp and #testPrintEmbeddedModeHelp
  flink-table/flink-sql-client/src/test/resources/cli/all-mode-help.out
  flink-table/flink-sql-client/src/test/resources/cli/embedded-mode-help.out
Labels: component=TableSQL/Client

#26012 [FLINK-37170][ci] Removes 1.18 version from GHA nightly builds
  .github/workflows/nightly-trigger.yml
Labels: component=BuildSystem/CI

#26016 [FLINK-37173][build] Fix license check issue in JDK11 build
  flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
Labels: component=BuildSystem/CI

#26024 [FLINK-37098] Fix UnresolvedSchema of QueryOperationCatalogView
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java
Labels: component=TableSQL/Planner

#26041 [BP-1.19][FLINK-36348][test] Fix the Netty shuffle direct memory test by increase the direct memory of TM
  flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh
Labels: component=Tests

#26042 [BP-1.20][FLINK-36348][test] Fix the Netty shuffle direct memory test by increase the direct memory of TM
  flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh
Labels: component=Tests

#26019 [FLINK-37076][table-planner] Support PTFs until ExecNode level
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
  flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RexTableArgCall.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/ExecNodeGraphGenerator.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonDeserializer.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerializer.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecProcessTableFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalTableFunctionScan.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalProcessTableFunction.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalProcessTableFunctionRule.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalConstantTableFunctionScanRule.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalConstantTableFunctionScanRule.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
  flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/ShortcutUtils.java
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalTableFunctionScan.scala
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
  flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerdeTest.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java
  flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.xml
Labels: component=TableSQL/Planner

#26025 [FLINK-37182][tests] Remove temp partition files created during test.
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
Labels: component=Tests

#26031 [FLINK-37035][release] Add new version 2.1 and update GHA nightly build versions
  .github/workflows/nightly-trigger.yml
  flink-annotations/src/main/java/org/apache/flink/FlinkVersion.java
Labels: component=ReleaseSystem

#26032 [FLINK-37035][release] Build doc for release-2.0 branch
  .github/workflows/docs.yml
Labels: component=ReleaseSystem

#26026 [FLINK-37183][clients] Fix symbolic links not being followed in "usrlib"
  flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java
  flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
  flink-clients/src/test/java/org/apache/flink/client/testjar/ClasspathProviderExtension.java
Labels: component=Client/JobSubmission

#26028 [FLINK-37183][clients] Fix symbolic links not being followed in "usrlib"
  flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java
  flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
  flink-clients/src/test/java/org/apache/flink/client/testjar/ClasspathProviderExtension.java
Labels: component=Client/JobSubmission

#26027 [FLINK-37183][clients] Fix symbolic links not being followed in "usrlib"
  flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java
  flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
  flink-clients/src/test/java/org/apache/flink/client/testjar/ClasspathProviderExtension.java
Labels: component=Client/JobSubmission

#26038 [FLINK-37098] Fix UnresolvedSchema of QueryOperationCatalogView
  flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java
  flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java
Labels: component=TableSQL/Planner

#26053 [FLINK-36838][state/forst] Fix the deadlock when quit forst state backend
  flink-dist/src/main/resources/META-INF/NOTICE
  flink-state-backends/flink-statebackend-forst/pom.xml
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
Labels: component=Runtime/StateBackends

#26054 [BP-2.0][FLINK-36838][state/forst] Fix the deadlock when quit forst state backend
  flink-dist/src/main/resources/META-INF/NOTICE
  flink-state-backends/flink-statebackend-forst/pom.xml
  flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
Labels: component=Runtime/StateBackends

#26043 [FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4
  docs/content/docs/deployment/memory/mem_tuning.md
Labels: component=<none>

#26056 [BP-2.0][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4
  docs/content/docs/deployment/memory/mem_tuning.md
Labels: component=<none>

#26044 [BP-1.20][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4
  docs/content/docs/deployment/memory/mem_tuning.md
Labels: component=<none>

#26045 [BP-1.19][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4
  docs/content/docs/deployment/memory/mem_tuning.md
Labels: component=<none>

#25956 [1.19][FLINK-37100][tests] Fix `test_netty_shuffle_memory_control.sh` with Netty4 RPC
  flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh
Labels: component=<none>

#25955 [1.20][FLINK-37100][tests] Fix `test_netty_shuffle_memory_control.sh` with Netty4 RPC
  flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh
Labels: component=<none>

#26033 [FLINK-35578][state/rocksdb] Bump frocksdbjni to 8.10.0-ververica-1.0
  flink-dist/src/main/resources/META-INF/NOTICE
  flink-state-backends/flink-statebackend-rocksdb/pom.xml
Labels: component=Runtime/StateBackends

#26034 [FLINK-37181][build] Fix MacOS sha256sum tool compile error
  mvnw
Labels: component=BuildSystem

#26057 [FLINK-37148][docs] Add documents for DataStream V2
  docs/content.zh/_index.md
  docs/content.zh/docs/dev/datastream-v2/_index.md
  docs/content.zh/docs/dev/datastream-v2/building_blocks.md
  docs/content.zh/docs/dev/datastream-v2/builtin-funcs/_index.md
  docs/content.zh/docs/dev/datastream-v2/builtin-funcs/joining.md
  docs/content.zh/docs/dev/datastream-v2/builtin-funcs/windows.md
  docs/content.zh/docs/dev/datastream-v2/context_and_state_processing.md
  docs/content.zh/docs/dev/datastream-v2/overview.md
  docs/content.zh/docs/dev/datastream-v2/time-processing/_index.md
  docs/content.zh/docs/dev/datastream-v2/time-processing/event_timer_service.md
  docs/content.zh/docs/dev/datastream-v2/time-processing/processing_timer_service.md
  docs/content.zh/docs/dev/datastream-v2/watermark.md
  docs/content/_index.md
  docs/content/docs/dev/datastream-v2/_index.md
  docs/content/docs/dev/datastream-v2/building_blocks.md
  docs/content/docs/dev/datastream-v2/builtin-funcs/_index.md
  docs/content/docs/dev/datastream-v2/builtin-funcs/joining.md
  docs/content/docs/dev/datastream-v2/builtin-funcs/windows.md
  docs/content/docs/dev/datastream-v2/context_and_state_processing.md
  docs/content/docs/dev/datastream-v2/overview.md
  docs/content/docs/dev/datastream-v2/time-processing/_index.md
  docs/content/docs/dev/datastream-v2/time-processing/event_timer_service.md
  docs/content/docs/dev/datastream-v2/time-processing/processing_timer_service.md
  docs/content/docs/dev/datastream-v2/watermark.md
  docs/static/fig/datastream/one-input-partitioning.png
  docs/static/fig/datastream/one-input-state-access.png
  docs/static/fig/datastream/two-input-state-access.png
Labels: component=<none>

#26010 [FLINK-36905] Update Chinese doc on serialization to reflect the latest changes in Flink 2.0
  docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md
  docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/third_party_serializers.md
  docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
Labels: component=Documentation, component=API/TypeSerializationSystem

#26050 [FLINK-37138][sql-gateway] Fix failed SqlYARNApplicationITCase in hadoop3 profile
  flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptRunner.java
Labels: component=BuildSystem/CI

#26072 [FLINK-37218][network] Avoid repeatedly reading the broadcast buffer from the sort-merge shuffle data file while accumulating small buffers from multiple sub-partitions.
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileReader.java
  flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java
  flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
Labels: component=Runtime/Network

#26086 [FLINK-37214][runtime] Refactors test to use proper Executor service for the main thread
  flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java
Labels: component=Tests, component=Runtime/Task
